# NumPy is the fundamental package for scientific computing with Python. It contains among other things:

    a powerful N-dimensional array object

    sophisticated (broadcasting) functions

    tools for integrating C/C++ and Fortran code

    useful linear algebra, Fourier transform, and random number capabilities

    Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 
    Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np       # Import numpy module and use np as alliasing name

In [2]:
a=np.array([])     # Way to create empty array

In [3]:
type(a)       #type of numpy array is ndarray.

numpy.ndarray

In [4]:
a                  # Default Data type  of array objects is float64

array([], dtype=float64)

##### Ways to create empty numpy array

In [5]:
a = np.array([])
print("An empty array: ",a)

a1  = np.arange(10)
print("Array using arange method: ",a1)

a2 = np.array(range(10))             # arange([start,] stop[, step,], dtype=None)
print("Array using range method: ",a2)

a3 = np.linspace(1,10,10,retstep=False)     # Data type of array elements is float64. It generate 10 values in between 1 and 10 with linear space of 1
print("Array using linspace method: ",a3)   # retstep gives difference between two neighbouring elements

a4 = np.random.random(10)     # It generate any 10 random values in the range 0 and 1
print("Array using random method: ",a4)

a5 = np.random.randn(10)      # It generate any 10 random values in the range -3 and +3
print("Array using randn method: ",a5)

a6 = np.random.uniform(low=-1, high=1,size=10)      # uniform distribution is generally from -1 to +1(Exclusive)
print("Array using random uniform method: ",a6)

a7 = np.random.normal(loc=-3, scale=3,size=(4,4))     # loc- mean of the distribution
print("Array using random normal method: ",a7)                                                      # scale-standard deviation (must be positive)

a8 = np.random.random_sample((4,5))  # Return random floats in the half-open interval [0.0, 1.0).
print("Array using random sample method: ",a7)

'''
(b - a) * random_sample() + a
#Three-by-two array of random numbers from [-5, 0):

#>>> 5 * np.random.random_sample((3, 2)) - 5
#array([[-3.99149989, -0.52338984], # random
#       [-2.99091858, -0.79479508],
#       [-1.23204345, -1.75224494]])
'''

a9 = np.random.rand(10)       # It generate any 10 random values in the range 0 and 1, 1 is exclusive
print("Array using rand method: ",a9)

a10=np.random.rand(2,2,4)   # 2 blocks, 2 rows, 2 columns
print("3-d Array using rand method: ",a10)

a11 = np.random.randint(low = 1, high = 10,size = (4,4))    # It generates an array of shape (2,3) with low inclusive and high exclusive 
print("Array using randint method:\n",a11)

a12 = np.zeros(shape = (4,4))                           # It generates an array of shape (2,2) with all values set to zero
print("Array of given shape with all zeros:\n",a12)   
             
a13 = np.ones(shape = (4,4))                            # It generates an array of shape (2,2) with all values set to one
print("Array of given shape with all ones:\n",a13)

a14 = np.identity(4)                         # It generates an array of shape (2,2) with all diagonal elements one and non-diagonal elements are zoros
print("Array of identity array using identity method:\n",a14)

a15 = np.eye(4)
print("Array of identity array using eye method:\n",a15)

a16 = np.full(shape = (4,4),fill_value = 10)    # It generates an array of shape (2,2) with all values set to value of fill_value
print("Array of given shape with all values as input:\n",a16)

An empty array:  []
Array using arange method:  [0 1 2 3 4 5 6 7 8 9]
Array using range method:  [0 1 2 3 4 5 6 7 8 9]
Array using linspace method:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array using random method:  [0.12418497 0.54487315 0.49434737 0.52959663 0.68915564 0.71712562
 0.72480582 0.56248742 0.40565746 0.07591221]
Array using randn method:  [ 0.44180552 -1.4583747   1.28049901 -0.42285496  0.38070678 -1.32343687
  0.06079029 -1.26473716 -0.26367672  0.54944925]
Array using random uniform method:  [-0.67752676 -0.21873676  0.65953057 -0.75215304 -0.83789248 -0.09622814
 -0.11826534 -0.36988156 -0.88669451 -0.13564436]
Array using random normal method:  [[-0.93062361 -4.79420072  4.14718934 -4.94343696]
 [-2.56796905 -1.12729251 -0.41334651 -2.38668525]
 [ 1.70255119 -2.38620434 -3.12973673 -5.01641544]
 [-5.14263942 -3.61349909 -3.75931747 -0.06273315]]
Array using random sample method:  [[-0.93062361 -4.79420072  4.14718934 -4.94343696]
 [-2.56796905 -1.12729251 -0.4133

##### To deal with data type of array elements

In [6]:
a = np.full(shape = (4,4),fill_value = 10,dtype = 'int16')    
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int16)

In [7]:
a.astype('float64')        

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

##### A sequence used for upasting while dealing with hetrogeneous data
int=>float=>complex=>boolean=>string=>object is upcasting

##### To chack array dimenssions

In [8]:
a.ndim         

2

##### To check memory allocation to array in Hex

In [9]:
a.data

##### To check shape of array
Shape represent number of rows and columns in an array

In [10]:
a.shape

(4, 4)

##### To check number of array elements 

In [11]:
a.size

16

##### Way to change shape of array

In [12]:
a.reshape(4,4)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int16)

In [13]:
#1D: 28                                                     []
#2D(rows,column): (4,7) (7,4) (2,14) (14,2) (1,28) (28,1)   [[],[],[]]
#3D(block,row,column): (2,2,7) (7,4,4) (2,14,1) (1,1,28)    [[[],[],[]]]

##### To check size of each array element
data type of array element is int16     16/8(size of byte)=2 bytes

In [14]:
a.itemsize      

2

In [15]:
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int16)

##### Ways to convert nd-array to 1d- array and to change shape of array
It can be done using two methods:
1. ravel()
Defualt data type of array items is float
Ravel is a method which converts ndarray to 1d.
It is a library function .
It creates deep copy.
It is faster and require less storage
2. flatten()
Another method to convert ndarray to 1d
It is a method associated with numpy so cant be used with other objects
It create shallow copy. i.e. create another object and it cant persist changes
It is slower and require more memory
3. resize

In [16]:
a.ravel()       # Shape of origional array remain unchanged 

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=int16)

In [17]:
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int16)

In [18]:
a.flatten()    # Shape of origional array remain unchanged   

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=int16)

In [19]:
a.resize(16)     # It is 3rd approach to convert nd to 1d
a                # resize modify array shape permanantly 

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=int16)

In [20]:
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=int16)

In [21]:
a.shape=(8,2)    # 4th approach to convert nd array to 1d. changes made are permanant.
a

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]], dtype=int16)

In [22]:
a

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]], dtype=int16)

In [23]:
e=np.arange(16).reshape(4,4) 
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
e.reshape(8,-1)      # In reshape we can put -1 for either of the dimwnsion.
                     #changes in dimensions using reshape are temporary.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [25]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### To access diagonal elements of array

In [26]:
np.diagonal(a)   

array([10, 10], dtype=int16)

##### To create list of an array elements
Each nested list corresponds to row

In [27]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
l=e.tolist()              
l

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

##### Ways to access array elements
We can access it by indexing and slicing

In [29]:
l[0]=[1,2,2,3]             # it returns first row of array
l                          # We can modify it by indexing and slicing

[[1, 2, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [30]:
l[0][0]     # We can access single elment of list using row and column indexing
            # It cant reflect changes in origional nd array

1

In [31]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
l1=list(np.ravel(e))    # By converting nd array to 1D and then typecasting we get list as a whole
l1                      # nd to 1d array conversion can be done using different methods

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [33]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
e[0]=[11,12,13,14]    # Accessing and modifyying array elements using indexing
e

array([[11, 12, 13, 14],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
e[0][1]=22     # modifying single element
e[0][1]

22

In [36]:
e

array([[11, 22, 13, 14],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
e[:,:2] =[[3,4],[5,6],[7,8],[9,10]]     # To access all rows and first two columns of array
e

array([[ 3,  4, 13, 14],
       [ 5,  6,  6,  7],
       [ 7,  8, 10, 11],
       [ 9, 10, 14, 15]])

In [38]:
e[0][1:3]      # To access 4 and 3 i.e. elements of first row and column1 and 2

array([ 4, 13])

In [39]:
e[:,-1]       # It gives all rows of last column horizontally

array([14,  7, 11, 15])

In [40]:
e[:,-1:]       # It gives all rows of last column vertically

array([[14],
       [ 7],
       [11],
       [15]])

##### in slicing if we apply index==> it will give 1D data
##### and if we apply slicing in slicing then ==> it will give 2D data
##### Slicing to modify multiple elements

##### Methods to convert row to column and column to rows

In [41]:
e

array([[ 3,  4, 13, 14],
       [ 5,  6,  6,  7],
       [ 7,  8, 10, 11],
       [ 9, 10, 14, 15]])

In [42]:
e.transpose()               # To take transpose of array

array([[ 3,  5,  7,  9],
       [ 4,  6,  8, 10],
       [13,  6, 10, 14],
       [14,  7, 11, 15]])

In [43]:
e.T                         # To take transpose of array

array([[ 3,  5,  7,  9],
       [ 4,  6,  8, 10],
       [13,  6, 10, 14],
       [14,  7, 11, 15]])

##### Arithmatic operations on nd-array

In [44]:
a=np.array([4,2,5,3])
a

array([4, 2, 5, 3])

In [45]:
b=np.array([7,8])
b

array([7, 8])

In [46]:
#a+b                  addition is not posible as bothe arrays are with shapes (4,) (2,) 
x=b[:,np.newaxis]    # convert 1D to 2D. 
x                    # Origional values as first column and new axis as second column   

array([[7],
       [8]])

In [47]:
a+x

array([[11,  9, 12, 10],
       [12, 10, 13, 11]])

##### Ways to expand dimenssions of array

In [48]:
arr=np.arange(5*5).reshape(5,5)
print(arr.shape)

arr1= np.expand_dims(arr,axis=(5,2,1,4,3))     # Axis should be unique up to number of elements
print(arr1.shape)                              # We can expand dimensions by any number 

(5, 5)
(5, 1, 1, 1, 1, 1, 5)


##### Combining multiple arrays

In [49]:
a=np.array(range(16)).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
b=np.array(range(11,15)).reshape(1,4)
b

array([[11, 12, 13, 14]])

In [51]:
np.append(a,b)           # append will convert nd array to 1d and then appent values at the end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 11,
       12, 13, 14])

In [52]:
np.append(a,b,axis=0)    # both arrays should be of same dimensions

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [11, 12, 13, 14]])

In [53]:
c=np.array(range(11,15)).reshape(4,1)
c

array([[11],
       [12],
       [13],
       [14]])

In [54]:
np.append(a,c,axis=1)

array([[ 0,  1,  2,  3, 11],
       [ 4,  5,  6,  7, 12],
       [ 8,  9, 10, 11, 13],
       [12, 13, 14, 15, 14]])

In [55]:
np.concatenate((a,b))            #columnwise as default value of axis is 0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [11, 12, 13, 14]])

In [56]:
np.concatenate((a,c),axis=1)     #rowwise

array([[ 0,  1,  2,  3, 11],
       [ 4,  5,  6,  7, 12],
       [ 8,  9, 10, 11, 13],
       [12, 13, 14, 15, 14]])

##### To add values in between or at specified index
#Insert values along the given axis before the given indices.
#==>(arr,index,values,axis)
np.insert(x,3,100,axis=0)

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.insert(a,2,100,axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100, 100, 100, 100],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [59]:
np.insert(a,2,100,axis=1)

array([[  0,   1, 100,   2,   3],
       [  4,   5, 100,   6,   7],
       [  8,   9, 100,  10,  11],
       [ 12,  13, 100,  14,  15]])

In [60]:
np.insert(a,2,[100,200,300,400],axis=1)

array([[  0,   1, 100,   2,   3],
       [  4,   5, 200,   6,   7],
       [  8,   9, 300,  10,  11],
       [ 12,  13, 400,  14,  15]])

##### Use of condition as indexing to access a part of an array

In [61]:

a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
a<10         # To generate boolean matrix specifying condition satisfaction

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [63]:
np.where(a<10,a,-a)    # Maintain number as it is if condition is satisfied else change its sign

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9, -10, -11],
       [-12, -13, -14, -15]])

In [64]:
a[a==0]=1111       # If condition satisfies then update value
a

array([[1111,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [65]:
a=np.full(16,fill_value=10).reshape(4,4)    # To create an array with all values initialised to 10
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [66]:
b=np.full((4,4),fill_value=20)
b

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

##### Create list of arrays

In [67]:
list(a)       # Create list of arrays

[array([10, 10, 10, 10]),
 array([10, 10, 10, 10]),
 array([10, 10, 10, 10]),
 array([10, 10, 10, 10])]

##### Statistic on nd- array

In [68]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
a.min()                # To get minimum value of array if axis is specified then it gives minimum value axis wise

0

In [70]:
a.max(axis=0)          # To get maximum value of array if axis is specified then it gives maximum value axis wise

array([12, 13, 14, 15])

In [71]:
a.mean(axis=1)        # To get average value of array if axis is specified then it gives average value axis wise

array([ 1.5,  5.5,  9.5, 13.5])

In [72]:
a.std(axis=0)         # To get standard deviation value of array if axis is specified then it gives standard deviation value axis wise

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [73]:
a.sum()                # To get addition of array values if axis is specified then it gives addition axis wise

120

In [74]:
a.prod()               # To get dot product of array values if axis is specified then it gives dot product axis wise

0

In [75]:
np.matmul(a,b)         # To get cross product of array values 

array([[ 120,  120,  120,  120],
       [ 440,  440,  440,  440],
       [ 760,  760,  760,  760],
       [1080, 1080, 1080, 1080]])

In [76]:
a.cumsum()             # To get cumulative addition of array values if axis is specified then it cumulative addition axis wise               

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120], dtype=int32)

In [77]:
a.cumprod()     # To get cumulative product of array values if axis is specified then it cumulative product axis wise 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)